milestone-trackers:
  DAMAGE_TAKEN:
    material: IRON_SWORD
    name: "&c&lDamage Taken"
    lore:
      - "&fDamage taken:"
      - "&c%value%"
    milestone-rewards:
      1000:
        name: "Iron Ingot"
        lore:
          - "Receive 2 iron ingots when you reach this!"
        type: GIVE_ITEM
        values:
          - "IRON_INGOT:2"
      2000:
        name: "Creative Mode!"
        lore:
          - "Receive creative mode when you reach this!"
        type: RUN_COMMAND
        values:
          - "gamemode creative %player%"
