messages:
  locked-lore: # lore to add onto the bottom of a reward item if locked
    - ''
    - '&eThreshold: &c%threshold%'
    - '&eYour Progress: &c%progress%'
    - '&c✖ Locked!'
  unlocked-lore: # lore to add onto the bottom of a reward item if locked
    - ''
    - '&fThreshold: %threshold%'
    - '&fYour Progress: %progress%'
    - '&a✔ Unlocked!'

  milestone-unlocked-message:
    - ''
    - '&a&lMILESTONE &8> %message%'
    - ''
milestone-trackers:
  DAMAGE_TAKEN:
    material: IRON_SWORD
    name: '&c&lDamage Taken'
    lore:
      - '&fDamage taken: &c%value%'
    milestone-rewards:
      '1000':
        name: '&c&lIron Ingot'
        lore:
          - '&7&o(Receive 2 iron ingots when you reach this!)'
        message: "You took 1000 damage!"
        type: GIVE_ITEM
        values:
          - IRON_INGOT:2
      '2000':
        name: '&c&lCreative Mode!'
        lore:
          - '&7&o(Receive creative mode when you reach this!)'
        message: "You took 2000 damage!"
        type: RUN_COMMAND
        values:
          - gamemode creative %player%
